### ISSUE TITLE
Nilpointer exception for migration stored in bindata

### ISSUE THREAD

**Issue by ekarlso** [mattes/migrate#275]
Hi, I am trying to run migrations towards the postgres interface of cockroachdb. 

My migration code is
```
func Connect() (*sql.DB, error) {
	db, err := sql.Open("postgres", "postgres://maxroach@192.168.99.100:30081/database?sslmode=disable")
	if err != nil {
		fmt.Println(err.Error())
	}
	return db, err
}

func DoMigrate() {
	log.Println("Attempting to migrate db")
	source := bindata.Resource(migrations.AssetNames(),
		func(name string) ([]byte, error) {
			return migrations.Asset(name)
		})
	migrateData, err := bindata.WithInstance(source)
	log.Println("Migrating from bindata")

	db, err := Connect()
	if err != nil {
		log.Fatalln(err.Error())
	}

	log.Println("Connected, attempting to migrate")
	migrateDriver, err := postgres.WithInstance(db, &postgres.Config{})

	//m, err := migrate.NewWithSourceInstance("go-bindata", d, "postgres://database/bookr")
	m, err := migrate.NewWithInstance("go-bindata", migrateData, "postgres", migrateDriver)
	if err != nil {
		log.Fatalln(err.Error())
		return
	}
	m.Up()
}
```

Results in a crash with a nil pointer dereference though I thought that I havent passed anything that is nil and the DB isnt errorign either earlier when connecting?

2017/09/12 15:19:13 Attempting to migrate db
2017/09/12 15:19:13 Migrating from bindata
2017/09/12 15:19:13 Connected, attempting to migrate
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x6a273c]

goroutine 8 [running]:
panic(0x969160, 0xc82000a170)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/mattes/migrate.(*Migrate).lock.func3(0xc82007c480, 0xc82001e720)
	/home/ekarlso/projects/go/src/github.com/mattes/migrate/migrate.go:867 +0x3c
created by github.com/mattes/migrate.(*Migrate).lock
	/home/ekarlso/projects/go/src/github.com/mattes/migrate/migrate.go:873 +0x175

**Comment by ekarlso** [comment]
Nevermind me, had wrong db name..
